import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import Sidebar from "./layouts/Sidebar";
import Header from "./layouts/Header";

const font = Epilogue({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main>
          <div className="border-t">
            <div className="bg-background">
              <div className="flex flex-grow">
                <div className="hidden lg:block w-[20%]">
                  <Sidebar></Sidebar>
                </div>
                <div className="col-span-3 overflow-auto lg:col-span-5 lg:border-l  w-[80%]">
                  <Header/>
                  <div className="px-6 lg:px-8">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
